--- 
before_script: "— npm install -g ionic cordova"
branches: "only — master"
deploy: 
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: www
  provider: pages
  skip-cleanup: true
  true: 
    branch: master
language: node_js
node_js: "— “8.9.4”"
script: "— ionic cordova build browser — prod"